### ISSUE TITLE
Example of deploying on AWS Lambda functions? 

### ISSUE THREAD

**Issue by jaanli** [filipre/signalbot#49]
Hi! I work with a therapist and they mentioned something like this would be very useful. Do you think it’s possible? 

Really excited to try it out :)

**Comment by filipre** [comment]
Hi @jaanli! 
I'm not sure if AWS lambdas are the correct solution for your use case. Both the signal api server as well as the bot framework would need to run continuously 24/7. In contrast, AWS lambdas are nice for individual requests and varying traffic. If you want to stay on AWS, I'd recommend to use the cheapest EC2 instance or any other VM. On Google, Cloud Run should work for you though you may need some custom logic to handle sudden restarts of containers. If you don't care about the cloud provider at all, I can recommend Oracle Cloud giving you a quite powerful VM for free, see [this](https://blogs.oracle.com/developers/post/how-to-set-up-and-run-a-really-powerful-free-minecraft-server-in-the-cloud) article. Let me know if you have more questions.

**Comment by jaanli** [comment]
Ooh thanks so much @filipre ! Would you recommend a VPS solution then (hertzner, digital ocean droplets I've used in the past)? Or just a Raspberry Pi Orange 5 (pretty okay specs for this) plugged in 24/7 near my computer?

**Comment by filipre** [comment]
Both a VPS or a Raspberry Pi is fine imo. At least I don't see a reason why one shouldn't work. With a VPS you don't have to worry about the hardware so that's probably a bit nicer and quicker to set up. What happens when you move stuff around in your room? Or when your router has connectivity issues? In my case, I connected the bot with some other things in my network so a VPS doesn't work.

**Comment by jaanli** [comment]
Ended up going with Lightspeed (3 months free right now, for a 2GB RAM 60GB SSD box, which should be plenty for this; https://aws.amazon.com/lightsail/pricing/ :)
